name: Review

on: [pull_request]

env:
  TARGET_DRUPAL_CORE_VERSION: 11

jobs:
  drupal-lint:
    runs-on: ubicloud-standard-4
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v6

    - name: Lint Drupal
      run: |
        docker compose --profile lint run drupal-lint

  drupal-check:
    runs-on: ubicloud-standard-4
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v6

    - name: Check Drupal compatibility
      run: |
        docker compose --profile lint run drupal-check

  e2e-test:
    runs-on: ubicloud-standard-4
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v6

    - uses: actions/checkout@v6
      with:
        repository: dxpr/dxpr_theme
        ref: 8.x
        path: dxpr_theme

    - name: Run E2E tests
      run: |
        docker compose --profile test run \
          -v ${{ github.workspace }}/dxpr_theme:/dxpr_theme \
          e2e-test
