<?php

declare(strict_types=1);

namespace Drupal\dxpr_theme_helper\Commands;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Extension\ThemeExtensionList;
use Drupal\Core\Cache\Cache;
use Drush\Commands\DrushCommands;
use Symfony\Component\Yaml\Yaml;

/**
 * Base class for all DXPR Theme Drush commands.
 *
 * Provides YAML output formatting, schema loading, validation,
 * and theme resolution consistent with drush_webmaster conventions.
 */
abstract class DxprThemeCommandsBase extends DrushCommands {

  /**
   * Cached settings schema.
   *
   * @var array|null
   */
  protected ?array $schema = NULL;

  /**
   * Switches to admin user for the duration of the Drush process.
   *
   * Does not call switchBack() — relies on process termination after
   * command execution. Call at the start of commands that need
   * elevated privileges.
   */
  protected function switchToAdmin(): void {
    // @phpstan-ignore-next-line
    if (!\Drupal::hasContainer()) {
      return;
    }

    try {
      /** @var \Drupal\Core\Session\AccountSwitcherInterface $accountSwitcher */
      // @phpstan-ignore-next-line
      $accountSwitcher = \Drupal::service('account_switcher');
      /** @var \Drupal\user\UserStorageInterface $userStorage */
      // @phpstan-ignore-next-line
      $userStorage = \Drupal::entityTypeManager()->getStorage('user');
      $admin = $userStorage->load(1);

      if ($admin) {
        $accountSwitcher->switchTo($admin);
      }
    }
    catch (\Exception $e) {
      // Silently fail if services aren't available yet.
    }
  }

  /**
   * Resolves the target DXPR theme.
   *
   * @param string|null $explicit
   *   An explicitly specified theme name, or NULL for auto-detection.
   * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
   *   The config factory.
   * @param \Drupal\Core\Extension\ThemeExtensionList $themeList
   *   The theme extension list.
   *
   * @return string
   *   The resolved theme machine name.
   *
   * @throws \RuntimeException
   *   If the theme cannot be resolved.
   */
  protected function resolveTheme(?string $explicit, ConfigFactoryInterface $configFactory, ThemeExtensionList $themeList): string {
    if ($explicit !== NULL) {
      if (!$themeList->exists($explicit)) {
        throw new \RuntimeException(sprintf('Theme "%s" not found.', $explicit));
      }
      if (!$this->isDxprTheme($explicit, $themeList)) {
        throw new \RuntimeException(sprintf('Theme "%s" is not a DXPR theme or DXPR subtheme. Only themes based on dxpr_theme are supported.', $explicit));
      }
      return $explicit;
    }

    // Auto-detect: use the default theme.
    $default = $configFactory->get('system.theme')->get('default');
    if ($default && $themeList->exists($default)) {
      if ($this->isDxprTheme($default, $themeList)) {
        return $default;
      }
    }

    // Fallback to dxpr_theme if it exists.
    if ($themeList->exists('dxpr_theme')) {
      return 'dxpr_theme';
    }

    throw new \RuntimeException('No DXPR theme found. Specify one with --theme.');
  }

  /**
   * Checks whether a theme is dxpr_theme or has dxpr_theme as an ancestor.
   *
   * Walks up the base theme chain to support multi-level subthemes
   * (e.g. sub-subthemes of dxpr_theme).
   *
   * @param string $themeName
   *   The theme machine name to check.
   * @param \Drupal\Core\Extension\ThemeExtensionList $themeList
   *   The theme extension list.
   *
   * @return bool
   *   TRUE if the theme is dxpr_theme or has dxpr_theme in its ancestry.
   */
  protected function isDxprTheme(string $themeName, ThemeExtensionList $themeList): bool {
    $current = $themeName;
    $visited = [];
    while ($current !== NULL) {
      if ($current === 'dxpr_theme') {
        return TRUE;
      }
      // Guard against circular references.
      if (isset($visited[$current])) {
        return FALSE;
      }
      $visited[$current] = TRUE;
      if (!$themeList->exists($current)) {
        return FALSE;
      }
      $info = $themeList->getExtensionInfo($current);
      $current = $info['base theme'] ?? NULL;
    }
    return FALSE;
  }

  /**
   * Loads the settings schema.
   *
   * Reads from dxpr_theme/data/settings-schema.json at runtime. The schema
   * is auto-generated by the theme's Grunt build from the PHP form definitions,
   * so it's always in sync with the GUI settings.
   *
   * @return array
   *   The settings schema keyed by setting name.
   */
  protected function loadSchema(): array {
    if ($this->schema !== NULL) {
      return $this->schema;
    }

    $path = NULL;

    // Primary: read from the installed dxpr_theme directory.
    // @phpstan-ignore-next-line
    if (\Drupal::hasContainer()) {
      try {
        // @phpstan-ignore-next-line
        $themePath = \Drupal::service('extension.list.theme')->getPath('dxpr_theme');
        $candidate = DRUPAL_ROOT . '/' . $themePath . '/data/settings-schema.json';
        if (file_exists($candidate)) {
          $path = $candidate;
        }
      }
      catch (\Exception $e) {
        // Theme not installed, fall through to fallback.
      }
    }

    // Fallback: bundled schema in this module (for environments where
    // dxpr_theme is not installed yet or for standalone testing).
    if ($path === NULL) {
      $path = dirname(__DIR__, 2) . '/data/settings-schema.json';
    }

    if (!file_exists($path)) {
      throw new \RuntimeException('Settings schema not found. Ensure dxpr_theme is installed and its data/settings-schema.json exists.');
    }

    $data = json_decode(file_get_contents($path), TRUE);
    if (!is_array($data)) {
      throw new \RuntimeException('Invalid settings schema JSON.');
    }

    // Remove _meta key.
    unset($data['_meta']);
    $this->schema = $data;
    return $this->schema;
  }

  /**
   * Gets available sections from the schema.
   *
   * @return array
   *   List of section names.
   */
  protected function getSections(): array {
    $schema = $this->loadSchema();
    $sections = [];
    foreach ($schema as $def) {
      if (isset($def['section']) && !in_array($def['section'], $sections)) {
        $sections[] = $def['section'];
      }
    }
    return $sections;
  }

  /**
   * Validates a value against the schema for a given key.
   *
   * @param string $key
   *   The setting key.
   * @param mixed $value
   *   The value to validate.
   *
   * @return array
   *   Array of error strings. Empty if valid.
   */
  protected function validateValue(string $key, mixed $value): array {
    $schema = $this->loadSchema();
    if (!isset($schema[$key])) {
      return [sprintf('Unknown setting "%s". Use dxt:config:list to see available settings.', $key)];
    }

    $def = $schema[$key];
    $errors = [];

    switch ($def['type']) {
      case 'boolean':
        if (!in_array($value, ['0', '1', 'true', 'false', TRUE, FALSE, 0, 1], TRUE)) {
          $errors[] = 'Value must be 0, 1, true, or false.';
        }
        break;

      case 'range':
        if (!is_numeric($value)) {
          $errors[] = sprintf('Value must be numeric. Valid range: %s-%s (step %s).', $def['min'], $def['max'], $def['step']);
        }
        elseif ((float) $value < $def['min'] || (float) $value > $def['max']) {
          $errors[] = sprintf('Value %s out of range. Valid: %s-%s (step %s).', $value, $def['min'], $def['max'], $def['step']);
        }
        break;

      case 'radios':
      case 'select':
        if (isset($def['options']) && is_array($def['options'])) {
          if (!array_key_exists((string) $value, $def['options'])) {
            $valid = implode(', ', array_keys($def['options']));
            $errors[] = sprintf('Invalid value "%s". Valid options: %s.', $value, $valid);
          }
        }
        break;

      case 'color':
        if ($value !== '' && !preg_match('/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/', (string) $value)) {
          $errors[] = 'Value must be a hex color (e.g. #ff0000 or #f00), or empty string.';
        }
        break;

      case 'checkboxes':
        // Accept comma-separated string or already-an-array.
        break;

      case 'textarea':
      case 'textfield':
      case 'path':
      case 'font':
      case 'theme_color':
      case 'serialized_palette':
        // Free-form text, no strict validation.
        break;
    }

    return $errors;
  }

  /**
   * Normalizes a value for storage based on schema type.
   *
   * @param string $key
   *   The setting key.
   * @param mixed $value
   *   The raw value.
   *
   * @return mixed
   *   The normalized value.
   */
  protected function normalizeValue(string $key, mixed $value): mixed {
    $schema = $this->loadSchema();
    if (!isset($schema[$key])) {
      return $value;
    }

    $def = $schema[$key];

    switch ($def['type']) {
      case 'boolean':
        return in_array($value, ['1', 'true', TRUE, 1], TRUE) ? 1 : 0;

      case 'range':
        // Store as string to match GUI form behavior. The theme's
        // _dxpr_theme_massage_values() checks is_string() before
        // applying unit suffixes (e.g. rem conversion), so numeric
        // types would skip conversion and produce broken CSS.
        $num = (float) $value;
        return ($num == (int) $num) ? (string) (int) $num : (string) $num;

      case 'checkboxes':
        if (is_string($value)) {
          if ($value === '' || $value === '[]') {
            return [];
          }
          $items = array_map('trim', explode(',', $value));
          // Build Drupal-style associative array (key => key for selected
          // items) to match how Drupal's Form API stores checkbox values.
          $result = [];
          foreach ($items as $item) {
            $result[$item] = $item;
          }
          return $result;
        }
        return $value;

      case 'radios':
      case 'select':
      case 'textfield':
      case 'textarea':
      case 'path':
      case 'font':
      case 'theme_color':
      case 'color':
        // Cast to string to match GUI form behavior. Drupal forms
        // always submit values as strings; downstream code like
        // _dxpr_theme_massage_values() relies on is_string() checks.
        return (string) $value;

      default:
        return $value;
    }
  }

  /**
   * Rebuilds the DXPR Theme CSS cache.
   *
   * @param string $theme
   *   The theme machine name.
   */
  protected function rebuildCssCache(string $theme): void {
    // @phpstan-ignore-next-line
    $themePath = \Drupal::service('extension.list.theme')->getPath('dxpr_theme');
    $callbackFile = $themePath . '/dxpr_theme_callbacks.inc';
    if (file_exists($callbackFile)) {
      require_once $callbackFile;
      if (function_exists('dxpr_theme_css_cache_build')) {
        dxpr_theme_css_cache_build($theme);
      }
    }

    // Invalidate render and page caches so that drupalSettings JS variables
    // (header height, breakpoints, sticky behavior, etc.) injected by
    // dxpr_theme_preprocess_html() are regenerated from fresh config values
    // on the next page load. Without this, cached HTML serves stale JS
    // settings causing layout issues like oversized headers.
    Cache::invalidateTags(['rendered']);
  }

  /**
   * Outputs data as YAML.
   */
  protected function yaml(array $data, int $inline = 4): string {
    return Yaml::dump($data, $inline, 2);
  }

  /**
   * Returns a success response as YAML.
   */
  protected function success(string $message, array $data = []): string {
    return $this->yaml(array_merge([
      'success' => TRUE,
      'message' => $message,
    ], $data));
  }

  /**
   * Returns an error response as YAML.
   */
  protected function error(string $message, array $errors = []): string {
    $data = [
      'success' => FALSE,
      'message' => $message,
    ];
    if (!empty($errors)) {
      $data['errors'] = $errors;
    }
    return $this->yaml($data);
  }

  /**
   * Returns success response with items list.
   */
  protected function successList(array $items, array $extra = []): string {
    return $this->yaml(array_merge([
      'success' => TRUE,
      'count' => count($items),
      'items' => $items,
    ], $extra));
  }

}
