<?php

/**
 * @file
 * Render content with tabs and other display styles.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\quicktabs_accordion\Hook\QuicktabsAccordionHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function quicktabs_accordion_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(QuicktabsAccordionHooks::class)->help($route_name, $route_match);
}
